In [1]:
import numpy as np
loc_test = np.load('bball_data/loc_test_bball.npy')

In [2]:
np.info(loc_test)

class:  ndarray
shape:  (13845, 49, 5, 2)
strides:  (3920, 80, 16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1ea9600f040
byteorder:  little
byteswap:  False
type: float64


In [6]:
loc_test_springs15r1 = np.load('GRN_springs_15-100/loc_test_springs15r1.npy')
np.info(loc_test_springs15r1)

class:  ndarray
shape:  (2000, 99, 2, 15)
strides:  (23760, 240, 120, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1eacfad5040
byteorder:  little
byteswap:  False
type: float64


In [4]:
loc_test_springs15r1 = np.load('GRN_springs_15-100/loc_test_springs15r1.npy')
loc_test_springs15r2 = np.load('GRN_springs_15-100/loc_test_springs15r2.npy')
loc_test_springs15r3 = np.load('GRN_springs_15-100/loc_test_springs15r3.npy')

loc_test_springs15r1 = loc_test_springs15r1[:, :, :, :5]
loc_test_springs15r2 = loc_test_springs15r2[:, :, :, :5]
loc_test_springs15r3 = loc_test_springs15r3[:, :, :, :5]

loc_train_springs15r1 = np.load('GRN_springs_15-100/loc_train_springs15r1.npy')
loc_train_springs15r2 = np.load('GRN_springs_15-100/loc_train_springs15r2.npy')
loc_train_springs15r3 = np.load('GRN_springs_15-100/loc_train_springs15r3.npy')

loc_train_springs15r1 = loc_train_springs15r1[:, :, :, :5]
loc_train_springs15r2 = loc_train_springs15r2[:, :, :, :5]
loc_train_springs15r3 = loc_train_springs15r3[:, :, :, :5]

loc_valid_springs15r1 = np.load('GRN_springs_15-100/loc_valid_springs15r1.npy')
loc_valid_springs15r2 = np.load('GRN_springs_15-100/loc_valid_springs15r2.npy')
loc_valid_springs15r3 = np.load('GRN_springs_15-100/loc_valid_springs15r3.npy')

loc_valid_springs15r1 = loc_valid_springs15r1[:, :, :, :5]
loc_valid_springs15r2 = loc_valid_springs15r2[:, :, :, :5]
loc_valid_springs15r3 = loc_valid_springs15r3[:, :, :, :5]

In [5]:
# Transpose the array to swap the last two dimensions
loc_test_springs15r1_adapted = np.transpose(loc_test_springs15r1, axes=(0, 1, 3, 2))
loc_test_springs15r2_adapted = np.transpose(loc_test_springs15r2, axes=(0, 1, 3, 2))
loc_test_springs15r3_adapted = np.transpose(loc_test_springs15r3, axes=(0, 1, 3, 2))

loc_train_springs15r1_adapted = np.transpose(loc_train_springs15r1, axes=(0, 1, 3, 2))
loc_train_springs15r2_adapted = np.transpose(loc_train_springs15r2, axes=(0, 1, 3, 2))
loc_train_springs15r3_adapted = np.transpose(loc_train_springs15r3, axes=(0, 1, 3, 2))

loc_valid_springs15r1_adapted = np.transpose(loc_valid_springs15r1, axes=(0, 1, 3, 2))
loc_valid_springs15r2_adapted = np.transpose(loc_valid_springs15r2, axes=(0, 1, 3, 2))
loc_valid_springs15r3_adapted = np.transpose(loc_valid_springs15r3, axes=(0, 1, 3, 2))

print("Original shape:", loc_test_springs15r1.shape)
print("Transposed shape:", loc_test_springs15r1_adapted.shape)

Original shape: (2000, 99, 2, 5)
Transposed shape: (2000, 99, 5, 2)


In [6]:
vel_test_springs15r1 = np.load('GRN_springs_15-100/loc_test_springs15r1.npy')
vel_test_springs15r2 = np.load('GRN_springs_15-100/loc_test_springs15r2.npy')
vel_test_springs15r3 = np.load('GRN_springs_15-100/loc_test_springs15r3.npy')

vel_test_springs15r1 = vel_test_springs15r1[:, :, :, :5]
vel_test_springs15r2 = vel_test_springs15r2[:, :, :, :5]
vel_test_springs15r3 = vel_test_springs15r3[:, :, :, :5]

vel_train_springs15r1 = np.load('GRN_springs_15-100/loc_train_springs15r1.npy')
vel_train_springs15r2 = np.load('GRN_springs_15-100/loc_train_springs15r2.npy')
vel_train_springs15r3 = np.load('GRN_springs_15-100/loc_train_springs15r3.npy')

vel_train_springs15r1 = vel_train_springs15r1[:, :, :, :5]
vel_train_springs15r2 = vel_train_springs15r2[:, :, :, :5]
vel_train_springs15r3 = vel_train_springs15r3[:, :, :, :5]

vel_valid_springs15r1 = np.load('GRN_springs_15-100/loc_valid_springs15r1.npy')
vel_valid_springs15r2 = np.load('GRN_springs_15-100/loc_valid_springs15r2.npy')
vel_valid_springs15r3 = np.load('GRN_springs_15-100/loc_valid_springs15r3.npy')

vel_valid_springs15r1 = vel_valid_springs15r1[:, :, :, :5]
vel_valid_springs15r2 = vel_valid_springs15r2[:, :, :, :5]
vel_valid_springs15r3 = vel_valid_springs15r3[:, :, :, :5]

In [7]:
# Transpose the array to swap the last two dimensions
vel_test_springs15r1_adapted = np.transpose(vel_test_springs15r1, axes=(0, 1, 3, 2))
vel_test_springs15r2_adapted = np.transpose(vel_test_springs15r2, axes=(0, 1, 3, 2))
vel_test_springs15r3_adapted = np.transpose(vel_test_springs15r3, axes=(0, 1, 3, 2))

vel_train_springs15r1_adapted = np.transpose(vel_train_springs15r1, axes=(0, 1, 3, 2))
vel_train_springs15r2_adapted = np.transpose(vel_train_springs15r2, axes=(0, 1, 3, 2))
vel_train_springs15r3_adapted = np.transpose(vel_train_springs15r3, axes=(0, 1, 3, 2))

vel_valid_springs15r1_adapted = np.transpose(vel_valid_springs15r1, axes=(0, 1, 3, 2))
vel_valid_springs15r2_adapted = np.transpose(vel_valid_springs15r2, axes=(0, 1, 3, 2))
vel_valid_springs15r3_adapted = np.transpose(vel_valid_springs15r3, axes=(0, 1, 3, 2))

In [8]:
# Saving the new files
np.save('./GNR_springs_15-100_adapted/loc_test_springs15r1.npy', loc_test_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/loc_test_springs15r2.npy', loc_test_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/loc_test_springs15r3.npy', loc_test_springs15r3_adapted)

np.save('./GNR_springs_15-100_adapted/loc_train_springs15r1.npy', loc_train_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/loc_train_springs15r2.npy', loc_train_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/loc_train_springs15r3.npy', loc_train_springs15r3_adapted)

np.save('./GNR_springs_15-100_adapted/loc_valid_springs15r1.npy', loc_valid_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/loc_valid_springs15r2.npy', loc_valid_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/loc_valid_springs15r3.npy', loc_valid_springs15r3_adapted)

In [9]:
# Saving the new files
np.save('./GNR_springs_15-100_adapted/vel_test_springs15r1.npy', vel_test_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/vel_test_springs15r2.npy', vel_test_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/vel_test_springs15r3.npy', vel_test_springs15r3_adapted)

np.save('./GNR_springs_15-100_adapted/vel_train_springs15r1.npy', vel_train_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/vel_train_springs15r2.npy', vel_train_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/vel_train_springs15r3.npy', vel_train_springs15r3_adapted)

np.save('./GNR_springs_15-100_adapted/vel_valid_springs15r1.npy', vel_valid_springs15r1_adapted)
np.save('./GNR_springs_15-100_adapted/vel_valid_springs15r2.npy', vel_valid_springs15r2_adapted)
np.save('./GNR_springs_15-100_adapted/vel_valid_springs15r3.npy', vel_valid_springs15r3_adapted)

In [2]:
edges_train_springs15r1 = np.load('GRN_springs_15-100/edges_train_springs15r1.npy')

In [3]:
np.info(edges_train_springs15r1)

class:  ndarray
shape:  (15, 15)
strides:  (120, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x23f44d639a0
byteorder:  little
byteswap:  False
type: int64


In [4]:
print(edges_train_springs15r1)

[[0 1 1 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 1 1 0 1 0 0 0 1]
 [0 1 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
